{{- if .Values.hive.spec.config.gcs.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: hive-gcs-credentials
data:
{{- if .Values.hive.spec.config.gcs.storageAccountName }}
  gcs-service-account-privat-key-id: {{ .Values.hive.spec.config.gcs.serviceAccountPrivateKeyId | b64enc | quote}}
{{- end }}
{{- if .Values.hive.spec.config.gcs.secretAccessKey }}
  gcs-service-account-private-key: {{ .Values.hive.spec.config.gcs.serviceAccountPrivateKey | b64enc | quote}}
{{- end }}
{{- end -}}
